import Head from 'next/head'
import bgstyle from "./Layout.module.css";

const Layout = (props) => {
  return (
    <div className={`min-h-screen px-10 md:px-20 pt-8 ${bgstyle.background}`}>
      <Head>
        <title>Coffee Connoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </div>
  );
};

export default Layout;
